apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: 
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service-svc
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000